config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :admin do
    root "homepage#login"
    get "home", to: "homepage#home"
    post "login", to: "session#create"
    delete "logout", to: "session#destroy"
    
    resources :users
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_many_attached :images
end 

app/models/user.rb
class User < ActiveRecord::Base
    enum role: {  admin: 0, user: 1 }
    has_secure_password
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
    include Admin::SessionHelper
    before_action :check_admin_login


    
    private

    def check_admin_login
        redirect_to admin_root_path unless admin_logged_in?
    end
end

app/controllers/admin/homepage_controller.rb
class Admin::HomepageController < Admin::AdminController
    skip_before_action :check_admin_login, only: [:login]
    def login
        redirect_to admin_home_path if admin_logged_in?
    end

    def home; end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product created"
      redirect_to admin_products_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product updated"
      redirect_to admin_products_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "Product deleted"
      redirect_to admin_products_path, status: :see_other
    else
      redirect_to request.referrer, status: :see_other
    end
  end

  private

    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :quantity, images: [])
    end
end

app/controllers/admin/session_controller.rb
class Admin::SessionController < Admin::AdminController
    skip_before_action :check_admin_login, only: [:create]
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password]) && user.admin?
            session[:user_id] = user.id
            redirect_to(admin_home_path)
        else
            flash[:error] = "Invalid email or password"
            redirect_to(admin_root_path)
        end
    end

    def destroy
        admin_log_out if admin_logged_in?
        redirect_to(admin_root_path)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    def index
        @users = User.user
    end

    def show
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Profile updated"
            redirect_to admin_users_path
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        if @user.destroy
            flash[:success] = "User deleted"
            redirect_to admin_users_path, status: :see_other
        else
            redirect_to request.referrer, status: :see_other
        end
    end

    private

        def find_user
            @user = User.find(params[:id])
        end

        def user_params
            params.require(:user).permit(:username, :email, :password, :password_confirmation)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/session_helper.rb
module Admin::SessionHelper
    def current_admin
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
            @current_user.admin? ? @current_user : nil 
        end
    end

    def admin_logged_in?
        !current_admin.nil?
    end

    def admin_log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homepage/login.html.erb
<!-- Pills navs -->
<div class="login-admin">

    <!-- Pills navs -->

    <!-- Pills content -->
    <div class="tab-content">
        <%= form_with url: admin_login_path do |form| %>
            <h1> Admin Login</h1>
            <div class="form-outline mb-4">
                <%= form.label :email, "Email" %>
                <%= form.email_field :email, class:"form-control" %>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                <%= form.label :password, "Password" %>
                <%= form.password_field :password, class:"form-control" %>
            </div>

            <!-- 2 column grid layout -->
            <div class="row mb-4">
                <div class="col-md-6 d-flex justify-content-center">
                <!-- Checkbox -->
                <div class="form-check mb-3 mb-md-0">
                    <input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />
                    <label class="form-check-label" for="loginCheck"> Remember me </label>
                </div>
                </div>

                <div class="col-md-6 d-flex justify-content-center">
                <!-- Simple link -->
                <a href="#!">Forgot password?</a>
                </div>
            </div>

        <!-- Submit bu\tton -->
            <%= form.submit "Sign in", class:"btn btn-primary btn-block mb-4" %>

            <!-- Register buttons -->
            <div class="text-center">
                <p>Not a member? <a href="#!">Register</a></p>
            </div>
        <% end %>
    </div>
</div>
<!-- Pills content -->

app/views/admin/products/_product_form.html.erb
<%= form_with(model: @product, url: url) do |f| %>
  <%= render 'shared/error_messages', object: @product %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :price %>
  <%= f.text_field :price, class: 'form-control' %>

  <%= f.label :quantity %>
  <%= f.text_field :quantity, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>

  <%= f.file_field :images, multiple: true %><br>

  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Edit product details</h1>

<div class="update-row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "product_form", url: admin_product_path(@product) %>
  </div>
</div>

app/views/admin/products/index.html.erb
<h2>Products (lmao)</h2>
<%= link_to new_admin_product_path do %>
    <div class="btn btn-primary"> Add new product
    </div>
<% end %>
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div>
            <% @products.each do |product| %>
                <div class="row p-2 bg-white border rounded">
                    <div class="col-md-3 mt-1">
                        <% if product.images.present? %>
                            <%= image_tag product.images.first, class: "img-fluid img-responsive rounded product-image" %>
                        <% else %>
                            <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930", class: "img-fluid img-responsive rounded product-image" %>
                        <% end %>
                        </div>
                    <div class="col-md-6 mt-1">
                        <h5><%= product.name%></h5>
                        <div class="mt-1 mb-1 spec-1">
                            <span>Product description:</span>
                        </div>
                        <p class="text-justify text-truncate para mb-0"><%= product.description %><br><br></p>
                    </div>
                    <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                        <div class="d-flex flex-row align-items-center">
                            <h4 class="mr-1"> <%= product.price %> </h4>
                        </div>
                        <h6 class="text-success">Quantity: <%= product.quantity %> </h6>
                        <div class="d-flex flex-column mt-4">
                            <%= link_to "Details", admin_product_path(product), class: "btn btn-primary btn-sm" %>
                            <%= link_to "Edit", edit_admin_product_path(product), class: "btn btn-outline-primary btn-sm mt-2" %>
                            <%= link_to "Delete", admin_product_path(product), data: { "turbo-method": :delete, turbo_confirm: "You sure?"},class: "btn btn-outline-primary btn-sm mt-2" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/products/new.html.erb
<h1>Add New Product</h1>

<div class="update-row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'product_form', url: admin_products_path %>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="card">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div id="demo" class="carousel slide" data-bs-ride="carousel">
            <% if @product.images.present? %>
              <!-- The slideshow/carousel -->
              <div class="carousel-inner">
                <% @product.images.each do |image| %>
                  <div class="carousel-item <%= image.id == @product.images.first.id ? "active" : "" %>">
                    <%= image_tag image, class: "d-block", style: "width:100%" %>
                  </div>
                <% end %>
              </div>
                
                <!-- Left and right controls/icons -->
              <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"></span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                <span class="carousel-control-next-icon"></span>
              </button>
            <% else %>
              <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg?20200913095930", class: "img-fluid img-responsive rounded product-image" %>
            <% end %>
          </div>
            
        </div>
        
        <!-- Carousel -->
        <div class="details col-md-6">
          <h3 class="product-title">
              <%= @product.name %>
          </h3>
          <p class="product-description">
              <%= @product.description %>
          </p>
          <h4 class="price">Price: 
              <span> <%= @product.price %> đ </span>
          </h4>
          <p class="vote"> In stock: <strong><%= @product.quantity %></strong></p>
          <div class="action">
            <button class="add-to-cart btn btn-default" type="button">Edit Item</button>
            <button class="like btn btn-default" type="button">
              <%= link_to admin_product_path(@product), data: { "turbo-method": :delete, turbo_confirm: "You sure?"} do %>
                <i class="bi bi-trash"></i>
              <% end %>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <th scope="row"><%= user.id %></th>
  <td><%= user.username %></td>
    <td><%= user.email %></td>
  <td><%= user.created_at %></td>
  <td>
    <%= link_to admin_user_path user do %>
        <i class="bi bi-eye"></i>
    <% end %>
    <%= link_to edit_admin_user_path user do %>
        <i class="bi bi-pen"></i>
    <% end %>
    <%= link_to admin_user_path(user), data: { "turbo-method": :delete, turbo_confirm: "You sure?" } do %>
      <i class="bi bi-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<h1>Update user information</h1>

<div class="update-row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: admin_user_path(@user), method: :patch) do |f| %>

        <%= render 'shared/error_messages' %>
        <%= f.label :username %>
        <%= f.text_field :username, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User name</th>
      <th scope="col">Email</th>
      <th scope="col">Created time</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "user", collection: @users %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<section class="vh-100" style="background-color: #f4f5f7;">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="height: 100vh; border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
              <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                alt="Avatar" class="img-fluid my-5" style="width: 150px;" />
              <div> 
                <h6>Username:</h6>
                <h5> <%= @user.username %> </h5>
                </div>

              <%# <i class="far fa-edit mb-5"></i> %>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>User Information</h6>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>User ID:</h6>
                    <%= @user.id%>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Email:</h6>
                    <%= @user.email%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 admin-profile-box">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">View Admin Profile</a></li>
            <li><a class="dropdown-item" ref="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= link_to "Log Out", admin_logout_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="sidebar">
    <li>
         <a class="active" href="#home">Home</a>
    </li>
     <li>
        <%= link_to "User Management", admin_users_path %>
    </li>
     <li>
        <%= link_to "Product Management", admin_products_path %>
    </li>
     <li>
         <a href="#home">Home</a>
    </li>
     <li>
         <a href="#home">Home</a>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternFoodAndDrink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <div class="container-fuild admin-layout">
      <% if admin_logged_in? %>
        <div class="row">
          <div class="col-2">
            <%= render "layouts/sidebar" %>
          </div>
          <div class="col-10">
            <%= render "layouts/header" %> 
            <div class="container-content">
              <%= render 'shared/flash' %>
              <%= yield %>
            </div>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert <%= "alert alert-#{message_type}" %>">
        <%= message %>
    </div>
<% end %>